CREATE TABLE Users(
  UserID INT PRIMARY KEY AUTO_INCREMENT,
  Username VARCHAR(50) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  TeamID INT NULL, 
  PlayerID INT NULL,
  Role VARCHAR(20) NOT NULL
  FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
  FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID)
);

CREATE TABLE Team (
  TeamID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL
);

CREATE TABLE Player (
  PlayerID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Number INT NOT NULL,
  Position VARCHAR(20) NOT NULL,
  TeamID INT NOT NULL,
  FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
);

CREATE TABLE Coach (
  CoachID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  TeamID INT NOT NULL,
  FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
);

CREATE TABLE Schedule (
  ScheduleID INT PRIMARY KEY AUTO_INCREMENT,
  GameDate DATE NOT NULL,
  GameTime TIME NOT NULL,
  LocationID INT NOT NULL,
  HomeTeamID INT NOT NULL,
  AwayTeamID INT NOT NULL,
  FOREIGN KEY (LocationID) REFERENCES Location(LocationID),
  FOREIGN KEY (HomeTeamID) REFERENCES Team(TeamID),
  FOREIGN KEY (AwayTeamID) REFERENCES Team(TeamID)
);

CREATE TABLE Location (
  LocationID INT PRIMARY KEY AUTO_INCREMENT,
  CityName VARCHAR(50) NOT NULL,
  ZipCode VARCHAR(10) NOT NULL
);